# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_name', models.CharField(max_length=500)),
                ('load_id', models.CharField(max_length=500)),
                ('load_data', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=500)),
                ('prod_id', models.CharField(max_length=500)),
                ('prod_data', models.FileField(upload_to=b'')),
            ],
        ),
    ]
