# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetRate', '0002_utilities_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadProfile',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
    ]
